- name: Create node_exporter cert dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
  loop:
   - "{{ node_exporter_tls_server_config.cert_file | dirname }}"
   - "{{ node_exporter_tls_server_config.key_file | dirname }}"
  tags:
    - monitoring

- name: Create node_exporter private key
  community.crypto.openssl_privatekey:
    path: "{{ node_exporter_tls_server_config.key_file }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"

- name: Create node_exporter certificate signing request (CSR)
  community.crypto.openssl_csr:
    path: "{{ node_exporter_tls_server_config.key_file | dirname }}/tls.csr"
    privatekey_path: "{{ node_exporter_tls_server_config.key_file }}"
    common_name: "{{ inventory_hostname }}"
    organization_name: Ansible
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"

- name: Create node_exporter cert
  openssl_certificate:
    path: "{{ node_exporter_tls_server_config.cert_file }}"
    csr_path: "{{ node_exporter_tls_server_config.key_file | dirname }}/tls.csr"
    privatekey_path: "{{ node_exporter_tls_server_config.key_file }}"
    provider: selfsigned
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
